# Generated by Django 6.0.5 on 2026-05-15 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_code', models.CharField(max_length=50, unique=True)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('door_open', models.BooleanField(default=False)),
                ('voltage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('faulty', 'Faulty')], default='offline', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_stock', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('high_temperature', 'High Temperature'), ('door_open', 'Door Open'), ('power_fault', 'Power Fault'), ('motor_fault', 'Motor Fault')], max_length=50)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridge')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.institution'),
        ),
        migrations.CreateModel(
            name='FridgeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('motor_pin', models.PositiveIntegerField()),
                ('ir_sensor_pin', models.PositiveIntegerField()),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='RestockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('voltage', models.FloatField()),
                ('door_open', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridge')),
            ],
        ),
        migrations.CreateModel(
            name='StockReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_level', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('fridge_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridgeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cashless', 'Cashless'), ('manual', 'Manual')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.fridge')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DairyApp.product')),
            ],
        ),
    ]
