# Generated by Django 6.0.5 on 2026-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
