# Generated by Django 6.0.5 on 2026-06-11 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0003_feedback_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='temp_threshold',
            field=models.FloatField(default=6.0, help_text='Temperature (°C) above which a high-temp alert is triggered'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_quantity',
            field=models.PositiveIntegerField(default=20, help_text='Quantity to order when an automatic restock order is created'),
        ),
        migrations.AddField(
            model_name='restockorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('faulty', 'Faulty')], db_index=True, default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='restockorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
