# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0004_improvements_indexes_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
