# Generated by Django 6.0.5 on 2026-06-16 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0005_fridge_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeslot',
            options={'ordering': ['fridge', 'slot_number']},
        ),
        migrations.AddField(
            model_name='fridgeslot',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='fridgeslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fridgeslot',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='DairyApp.fridge'),
        ),
        migrations.AlterField(
            model_name='fridgeslot',
            name='ir_sensor_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridgeslot',
            name='motor_pin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridgeslot',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_slots', to='DairyApp.product'),
        ),
        migrations.AlterField(
            model_name='fridgeslot',
            name='slot_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddConstraint(
            model_name='fridgeslot',
            constraint=models.UniqueConstraint(fields=('fridge', 'slot_number'), name='unique_slot_number_per_fridge'),
        ),
        migrations.AddConstraint(
            model_name='fridgeslot',
            constraint=models.CheckConstraint(condition=models.Q(('slot_number__gte', 1), ('slot_number__lte', 6)), name='fridge_slot_number_between_1_and_6'),
        ),
        migrations.AddConstraint(
            model_name='fridgeslot',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__lte', models.F('max_capacity'))), name='fridge_slot_stock_not_above_capacity'),
        ),
    ]
