# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DairyApp", "0006_alter_fridgeslot_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fridgeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("low_stock_threshold__lte", models.F("max_capacity"))
                ),
                name="fridge_slot_low_threshold_not_above_capacity",
            ),
        ),
    ]
